modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT" # License Schmicense

#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
    # The modid of the mod
    modId="tflostblocks" #mandatory
    version="${file.jarVersion}"
    displayName="Twilight Forest: The Lost Blocks"
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional
    displayURL="https://www.curseforge.com/minecraft/mc-mods/twilight-forest-the-lost-blocks"
    logoFile="icon.png"
    credits="Thanks to the original developers of Twilight Forest."
    authors="Kitteh6660"
    description='''Adds certain missing blocks to Twilight Forest.'''

[[dependencies.tflostblocks]] #optional
    modId="neoforge" #mandatory
    type="required"
    versionRange="[21.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tflostblocks]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tflostblocks]]
    modId="twilightforest"
    type="required"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"
